eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
     defaultZone: http://k9a304.p.ssafy.io:8762/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
