spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9a304.p.ssafy.io:3306/TEST?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: sugarmanager_service
    password: Icando304!
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

kafka:
  bootstrap-servers: k9a304.p.ssafy.io:9092,k9a304.p.ssafy.io:9093,k9a304.p.ssafy.io:9094
