server:
  port : 8080
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    include: db
  kafka:
    bootstrap-servers: k9a304.p.ssafy.io:9092,k9a304.p.ssafy.io:9093,k9a304.p.ssafy.io:9094
firebase : C:/Users/SSAFY/Desktop/S09P31A304/alarm/src/main/resources/firebase/sugar-manager-firebase-secretkey.json

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
